### ISSUE TITLE
Support for pointercancel?

### ISSUE THREAD

**Issue by mmocny** [uxify-ltd/performance-event-timing-polyfill#2]
I haven't done a very careful audit, but I see that interactions are measured until a set of events are measured.

However, sometimes pointer events will become scroll events and fire pointercancel, in which case you can wrap things up early.  Otherwise you will either buffer forever, or, potentially mix up with  future pointer events.

(Similarly pointer events lead to a contextmenu event, and then (depending on platform) might not have any of pointercancel nor pointerup/click events...)

**Comment by ivailo-uxify** [comment]
Thanks! Resolved in v0.5.0 :rocket:
